Warning -Use undefined parameter (dtprestr) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\test_bolt_b_implicit\bolted_connection_b.k line # 91
Warning -Use undefined parameter (bltforce) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\test_bolt_b_implicit\bolted_connection_b.k line # 91
Warning -Use undefined parameter (tload) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\test_bolt_b_implicit\bolted_connection_b.k line # 119
Warning -Use undefined parameter (tend) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\test_bolt_b_implicit\bolted_connection_b.k line # 120
Warning -Use undefined parameter (distx) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\test_bolt_b_implicit\bolted_connection_b.k line # 120
Warning -Use undefined parameter (tinfty) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\test_bolt_b_implicit\bolted_connection_b.k line # 121
 Time to read keyword file =  0.062 seconds
Message 0
Warning -Use undefined parameter (tdybir*0.99) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\test_bolt_b_implicit\control_implicit.k line # 47
 Time to read keyword file =  0.000 seconds
Message 0
 Time to read keyword file =  0.062 seconds
Message 0
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
Invalid entity ID!  ** Prog Error:
 Time to read keyword file =  0.062 seconds
Message 0
Warning -Use undefined parameter (dtprestr) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\Bolt_B_Explicit\bolted_connection_b.k line # 91
Warning -Use undefined parameter (bltforce) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\Bolt_B_Explicit\bolted_connection_b.k line # 91
Warning -Use undefined parameter (tload) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\Bolt_B_Explicit\bolted_connection_b.k line # 119
Warning -Use undefined parameter (tend) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\Bolt_B_Explicit\bolted_connection_b.k line # 120
Warning -Use undefined parameter (distx) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\Bolt_B_Explicit\bolted_connection_b.k line # 120
Warning -Use undefined parameter (tinfty) 
  Warning occurs in file C:\Users\Trey\Documents\GitHub\PILLARS-LSDyna\Bolt_B_Explicit\bolted_connection_b.k line # 121
 Time to read keyword file =  0.062 seconds
Message 0
